export const PROTOCOL_VERSION = 1
export const SUPPORTED_PROTOCOL_VERSIONS = [PROTOCOL_VERSION] as const
export const MAX_FRAME_BYTES = 4 * 1024 * 1024
export const MAX_TEXT_RESULT_BYTES = 50 * 1024
export const DEFAULT_REQUEST_TIMEOUT_MS = 15_000
export const MAX_REQUEST_TIMEOUT_MS = 60_000
